# Generated by Django 4.2.4 on 2023-08-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='intro',
            field=models.TextField(default='Hello'),
            preserve_default=False,
        ),
    ]
