# Generated by Django 4.2.4 on 2023-08-18 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('home', '0003_homepage_intro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='intro',
        ),
        migrations.AddField(
            model_name='homepage',
            name='bannerImage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='bannerText',
            field=models.TextField(default='hi', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='bannerTitle',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
