# Generated by Django 4.2.4 on 2023-08-18 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_homepage_intro_homepage_bannerimage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='bannerImage',
            new_name='banner_image',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='bannerText',
            new_name='banner_text',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='bannerTitle',
            new_name='banner_title',
        ),
    ]
